export const PUBSUB_NEW_ENROLLMENT = "PUBSUB_NEW_ENROLLMENT";
export const PUBSUB_NEW_USER_MESSAGE = "PUBSUB_NEW_USER_MESSAGE";
export const PUBSUB_NEW_MATCH = "PUBSUB_NEW_MATCH";
export const PUBSUB_NEW_CHILD_MATCH = "PUBSUB_NEW_CHILD_MATCH";